variables:
  # Avoid expensive initialization of dotnet cli, see: https://donovanbrown.com/post/Stop-wasting-time-during-NET-Core-builds
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1

stages:
  - stage: Build
    jobs:
      - job: 'Full_Build'
        pool:
          vmImage: windows-latest
        steps:
        - pwsh: |
            Import-Module .\tools\appveyor.psm1
            Invoke-AppveyorInstall -SkipPesterInstallation
            ./build.ps1 -Configuration 'Release' -All
            ./PSCompatibilityCollector/build.ps1 -Configuration 'Release'
          displayName: 'Full Build'
        - pwsh: |
            Write-Host "##vso[artifact.upload containerfolder=out;artifactname=out;]${env:Build_SourcesDirectory}/out"
  - stage: Test
    jobs:
      - job:
        strategy:
          matrix:
            Ubuntu_20_04:
              vmImage: ubuntu-20.04
            Ubuntu_22_04:
              vmImage: ubuntu-22.04
            mac_Latest:
              vmImage: macOS-latest
            Windows_Server2019_PowerShell_Core:
              vmImage: windows-2019
            Windows_Server2022_PowerShell_Core:
              vmImage: windows-2022
        pool:
          vmImage: $[ variables['vmImage'] ]
        steps:
        - template: templates/test-pwsh.yaml
      - job:
        strategy:
          matrix:
            Windows_Server2019_PowerShell_5_1:
              vmImage: windows-2019
              pwsh: true
            Windows_Server2022_PowerShell_5_1:
              vmImage: windows-2022
              pwsh: true
        pool:
          vmImage: $[ variables['vmImage'] ]
        steps:
        - template: templates/test-powershell.yaml
